tenant_id     = "your-tenant-id"
client_id     = "your-client-id"
client_secret = "your-client-secret"
resource_group_name = "restaurant-recommendation-api-resources"
location = "West Europe"
sql_admin_username = "sqladmin"
sql_admin_password = "H@Sh1CoR3!"