on:
  push:
    branches:
    - main
    - release/*
  pull_request:
    branches:
    - main
  workflow_dispatch:
  # Manually run

jobs:
  my_job:
    name: deploy to staging
    runs-on: ubuntu-22.04
