on:
  push:
    branches:
    - main
    - release/*
  pull_request:
    branches:
    - main
  workflow_dispatch:
  # Manually run

name: Python Docker Deployment to Azure App Service

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    env:
      APPLICATION_INSIGHTS_INSTRUMENTATION_KEY: ${{ secrets.APPLICATION_INSIGHTS_INSTRUMENTATION_KEY }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r restaurantsManage/requirements.txt

    - name: Run tests
      run: |
        python -m pytest restaurantsManage/tests/ --junitxml=test-results.xml
      continue-on-error: true

    - name: Upload Test Results
      uses: actions/upload-artifact@v2
      with:
        name: test-results
        path: restaurantsManage/tests/test-results.xml
      if: failure()

    - name: 'Login to Azure Container Registry'
      uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.AZURE_CONTAINER_REGISTRY }}.azurecr.io 
        username: ${{ secrets.ACR_USERNAME }} 
        password: ${{ secrets.ACR_PASSWORD }} 

    - name: 'Build Docker Image'
      run: |
        docker build -f restaurantsManage/Dockerfile -t ${{ secrets.AZURE_CONTAINER_REGISTRY }}.azurecr.io/restaurant-recommendation-appservice:${{ github.sha }}
    
    - name: 'Push Docker Image to ACR'
      run: |
        docker push ${{ secrets.AZURE_CONTAINER_REGISTRY }}.azurecr.io/restaurant-recommendation-appservice:${{ github.sha }} || exit 1

    - name: 'Deploy Docker Image to Azure App Service'
      uses: azure/webapps-deploy@v2
      with:
        app-name: restaurant-recommendation-appservice
        publish-profile: ${{ secrets.AZURE_APP_SERVICE_PUBLISH_PROFILE }}  # Set this in GitHub secrets
        images: ${{ secrets.AZURE_CONTAINER_REGISTRY }}.azurecr.io/restaurant-recommendation-appservice:${{ github.sha }}
